name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7 
  nearby_connections: ^1.1.1+1
  image_picker: ^0.6.5+3
  page_transition: ^1.1.5
  settings_ui: ^0.2.0
  flutter_map: any
  location: ^3.0.0
  cloud_firestore: ^0.11.0+2
  json_annotation: ^3.0.1
  flutter_wordpress: ^0.2.1
  flutter_html: ^0.11.1
  url_launcher: ^5.4.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"
  build_runner: ^1.0.0
  json_serializable: ^3.3.0

flutter_icons:
  image_path: "assets/images/virus-icon.png" 
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
     - assets/images/